"""Generated resume database model."""

from sqlalchemy import ForeignKey, Index, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class GeneratedResume(Base, TimestampMixin):
    """Tracking record for a resume generated by the external microservice."""

    __tablename__ = "generated_resumes"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id"), nullable=False)
    match_id: Mapped[int] = mapped_column(ForeignKey("match_results.id"), nullable=False)
    external_task_id: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="pending")
    resume_pdf_path: Mapped[str | None] = mapped_column(String(500), nullable=True)
    cover_letter_pdf_path: Mapped[str | None] = mapped_column(String(500), nullable=True)
    cover_letter_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    language: Mapped[str] = mapped_column(String(10), nullable=False, default="en")
    provider: Mapped[str] = mapped_column(String(50), nullable=False, default="anthropic")

    # Relationships
    user: Mapped["User"] = relationship()
    match_result: Mapped["MatchResult"] = relationship()

    __table_args__ = (
        Index("ix_generated_resume_match_id", "match_id"),
        Index("ix_generated_resume_external_task_id", "external_task_id"),
    )
